# Generated by Django 4.0.4 on 2022-05-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maanga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maanga_title', models.CharField(max_length=200, verbose_name='title')),
                ('maanga_text', models.TextField(verbose_name='text')),
                ('maanga_publ', models.DateTimeField(verbose_name='Publish date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name="commenator's name")),
                ('comment_text', models.CharField(max_length=200, verbose_name='comment text')),
                ('maanga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maangas.maanga')),
            ],
        ),
    ]
