# Generated by Django 4.0.4 on 2022-05-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maangas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_page', models.ImageField(upload_to='chapters', verbose_name='chapter page')),
            ],
        ),
    ]
